/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.com.tic.exec.Tecnico;

import java.io.File;
import java.net.URL;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.table.DefaultTableModel;
import src.com.tic.dao.TecnicoDAOimpl;
import src.com.tic.dao.UsuarioDAOimpl;
import src.com.tic.exec.JFrameLogin;
import src.com.tic.pojo.Incidencia;

/**
 *
 * @author alumno
 */
public class VistaTecnico extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaTecnico.class.getName());
    private HelpBroker hb;
    int idIncidencia;
    private int idUsuario;
    private UsuarioDAOimpl usuarioDAO = new UsuarioDAOimpl();

    private ArrayList<String> al;

    int idTecnico;

    TecnicoDAOimpl tecnicoDAO = new TecnicoDAOimpl();

    /**
     * Creates new form VistaTecnico
     */
    public VistaTecnico(int idUsuario, String usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jLabel3.setText("Hola, " + usuario + ". Otro día más en el curro");
        this.idUsuario = idUsuario;
        inicializarAyuda();
        try {
            al = usuarioDAO.getTiposIncidencias();
            refrescarComboBoxTipo(al);
            this.idTecnico = tecnicoDAO.hallarIdTecnico(idUsuario);
        } catch (Exception ex) {
            System.out.println("Error de búsqueda: " + ex.getMessage());
        }
        refrescarTabla(idTecnico);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTecnico = new javax.swing.JTable();
        jButtonAtenderIndicencia = new javax.swing.JButton();
        jButtonCerrarIndicencia = new javax.swing.JButton();
        jButtonAgregarTipo = new javax.swing.JButton();
        jButtonVerIndicencias = new javax.swing.JButton();
        jButtonVerIndicenciasConcretas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonVerIndicenciasTiempoConcreto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxTipoIncidencia = new javax.swing.JComboBox<>();
        jButtonSalir1 = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        jSpinnerDias = new javax.swing.JSpinner();
        jSpinnerAtenderId = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Otro dia mas en el curro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(277, 277, 277))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableTecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Incidencia", "estado", "result_cierre", "f_cierre", "f_entrada", "tipo_incidencia", "ID_Usuario", "ID_Tecnico", "descripcion", "Solucion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTecnicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTecnico);

        jButtonAtenderIndicencia.setText("Atender Indicencia");
        jButtonAtenderIndicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtenderIndicenciaActionPerformed(evt);
            }
        });

        jButtonCerrarIndicencia.setText("Cerrar Incidencia");
        jButtonCerrarIndicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarIndicenciaActionPerformed(evt);
            }
        });

        jButtonAgregarTipo.setText("Agregar tipo de Incidencia");
        jButtonAgregarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarTipoActionPerformed(evt);
            }
        });

        jButtonVerIndicencias.setText("Listar indicencias asignadas");
        jButtonVerIndicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerIndicenciasActionPerformed(evt);
            }
        });

        jButtonVerIndicenciasConcretas.setText("Listar tipo incidencia");
        jButtonVerIndicenciasConcretas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerIndicenciasConcretasActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo Indicencia");

        jButtonVerIndicenciasTiempoConcreto.setText("Listar incidencia cerradas en un tiempo");
        jButtonVerIndicenciasTiempoConcreto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerIndicenciasTiempoConcretoActionPerformed(evt);
            }
        });

        jLabel2.setText("Dias");

        jComboBoxTipoIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoIncidenciaActionPerformed(evt);
            }
        });

        jButtonSalir1.setBackground(new java.awt.Color(255, 102, 102));
        jButtonSalir1.setText("Salir");
        jButtonSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalir1ActionPerformed(evt);
            }
        });

        jButtonCerrarSesion.setText("Cerrar Sesion");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        jLabel4.setText("ID");

        jMenu1.setText("Ayuda");

        jMenuItemAyuda.setText("Abrir ayuda");
        jMenuItemAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemAyudaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemAyudaMousePressed(evt);
            }
        });
        jMenuItemAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAyudaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAyuda);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCerrarIndicencia)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinnerAtenderId, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAtenderIndicencia))
                            .addComponent(jButtonAgregarTipo)
                            .addComponent(jButtonVerIndicencias)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSalir1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCerrarSesion)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonVerIndicenciasTiempoConcreto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinnerDias, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(jButtonVerIndicenciasConcretas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTipoIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAtenderIndicencia)
                            .addComponent(jSpinnerAtenderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCerrarIndicencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAgregarTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVerIndicencias)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCerrarSesion)
                    .addComponent(jButtonVerIndicenciasConcretas)
                    .addComponent(jComboBoxTipoIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonSalir1)
                    .addComponent(jButtonVerIndicenciasTiempoConcreto)
                    .addComponent(jSpinnerDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarIndicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarIndicenciaActionPerformed
        jDialogCerrarIncidencia dCerrarIncidencia = new jDialogCerrarIncidencia(this, false);
        dCerrarIncidencia.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarIndicenciaActionPerformed

    private void jButtonAgregarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarTipoActionPerformed
        jDialogAgregarTipoIncidencia dAgregarTipoIncidencia = new jDialogAgregarTipoIncidencia(this, true);
        dAgregarTipoIncidencia.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarTipoActionPerformed

    private void jButtonAtenderIndicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtenderIndicenciaActionPerformed
        try {
            tecnicoDAO.atenderIncidencia((int) this.jSpinnerAtenderId.getValue());
            refrescarTabla(idTecnico);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonAtenderIndicenciaActionPerformed

    private void jTableTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTecnicoMouseClicked
        int fila = this.jTableTecnico.rowAtPoint(evt.getPoint());
        idIncidencia = (int) this.jTableTecnico.getValueAt(fila, 0);
        this.jSpinnerAtenderId.setValue(idIncidencia);
    }//GEN-LAST:event_jTableTecnicoMouseClicked

    private void jButtonVerIndicenciasConcretasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerIndicenciasConcretasActionPerformed
        refrescarTablaPorTipo(this.jComboBoxTipoIncidencia.getSelectedItem().toString());
    }//GEN-LAST:event_jButtonVerIndicenciasConcretasActionPerformed

    private void jButtonVerIndicenciasTiempoConcretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerIndicenciasTiempoConcretoActionPerformed
        try {
            ArrayList<Incidencia> al = tecnicoDAO.getIncidenciasBetweenFechas((int) (this.jSpinnerDias.getValue()));
            refrescarTablaBeetwen(al);
        } catch (Exception ex) {
            System.out.println("Error al hacer consulta de fechas: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonVerIndicenciasTiempoConcretoActionPerformed

    private void jButtonVerIndicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerIndicenciasActionPerformed
        refrescarTabla(this.idTecnico);
    }//GEN-LAST:event_jButtonVerIndicenciasActionPerformed

    private void jComboBoxTipoIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoIncidenciaActionPerformed
        
    }//GEN-LAST:event_jComboBoxTipoIncidenciaActionPerformed

    private void jButtonSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalir1ActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        JFrameLogin login = new JFrameLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void jMenuItemAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAyudaActionPerformed
        ponLaAyuda();    }//GEN-LAST:event_jMenuItemAyudaActionPerformed

    private void jMenuItemAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAyudaMouseClicked
        ponLaAyuda();    }//GEN-LAST:event_jMenuItemAyudaMouseClicked

    private void jMenuItemAyudaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAyudaMousePressed
        ponLaAyuda();
    }//GEN-LAST:event_jMenuItemAyudaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    public void refrescarTablaBeetwen(ArrayList<Incidencia> ai) {
        DefaultTableModel m = (DefaultTableModel) this.jTableTecnico.getModel();
        m.setNumRows(0);

        try {
            Incidencia i;
            for (int j = 0; j < ai.size(); j++) {
                i = ai.get(j);
                Object[] o = {
                    i.getIdIncidencia(),
                    i.getEstado(),
                    i.getResultado_cierre(),
                    i.getFechaCierre(),
                    i.getFechaEntrada(),
                    i.getTipoIncidencia(),
                    i.getIdUsuario(),
                    i.getIdTecnico(),
                    i.getDescripcionIncidencia(),
                    i.getDescripcionSolucion()
                };
                m.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar tabla incidencia");
        }
    }

    public void refrescarTablaPorTipo(String tipo) {
        DefaultTableModel m = (DefaultTableModel) this.jTableTecnico.getModel();
        m.setNumRows(0);

        Incidencia i = null;
        try {
            ArrayList<Incidencia> ai = (ArrayList<Incidencia>) tecnicoDAO.getIncidenciasByTipo(tipo);
            for (int j = 0; j < ai.size(); j++) {
                i = ai.get(j);
                Object[] o = {
                    i.getIdIncidencia(),
                    i.getEstado(),
                    i.getResultado_cierre(),
                    i.getFechaCierre(),
                    i.getFechaEntrada(),
                    i.getTipoIncidencia(),
                    i.getIdUsuario(),
                    i.getIdTecnico(),
                    i.getDescripcionIncidencia(),
                    i.getDescripcionSolucion()
                };
                m.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar tabla incidencia");
        }
    }

    public void refrescarComboBoxTipo(ArrayList<String> al) {
        for (String string : al) {
            this.jComboBoxTipoIncidencia.addItem(string);
        }
    }

    public void refrescarTabla(int IdTecnico) {
        DefaultTableModel m = (DefaultTableModel) this.jTableTecnico.getModel();
        m.setNumRows(0);

        Incidencia i = null;
        try {
            ArrayList<Incidencia> ai = (ArrayList<Incidencia>) tecnicoDAO.getIncidenciasAsignadas(IdTecnico);
            for (int j = 0; j < ai.size(); j++) {
                i = ai.get(j);
                Object[] o = {
                    i.getIdIncidencia(),
                    i.getEstado(),
                    i.getResultado_cierre(),
                    i.getFechaCierre(),
                    i.getFechaEntrada(),
                    i.getTipoIncidencia(),
                    i.getIdUsuario(),
                    i.getIdTecnico(),
                    i.getDescripcionIncidencia(),
                    i.getDescripcionSolucion()
                };
                m.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar tabla incidencia");
        }
    }

    private void ponLaAyuda() {
        hb.enableHelpOnButton(jMenuItemAyuda, "tecnico", null);
        hb.enableHelpKey(getRootPane(), "tecnico", null);
    }

    private void inicializarAyuda() {
        try {
            File fichero = new File("help" + File.separator + "helpset.hs");
            URL hsURL = fichero.toURI().toURL();

            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            hb = helpset.createHelpBroker();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarTipo;
    private javax.swing.JButton jButtonAtenderIndicencia;
    private javax.swing.JButton jButtonCerrarIndicencia;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonSalir1;
    private javax.swing.JButton jButtonVerIndicencias;
    private javax.swing.JButton jButtonVerIndicenciasConcretas;
    private javax.swing.JButton jButtonVerIndicenciasTiempoConcreto;
    private javax.swing.JComboBox<String> jComboBoxTipoIncidencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAyuda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerAtenderId;
    private javax.swing.JSpinner jSpinnerDias;
    private javax.swing.JTable jTableTecnico;
    // End of variables declaration//GEN-END:variables
}
