package src.com.tic.exec.Usuario;

import java.io.File;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.table.DefaultTableModel;
import src.com.tic.dao.UsuarioDAOimpl;
import src.com.tic.exec.JFrameLogin;
import src.com.tic.pojo.Incidencia;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author alumno
 */
public class VistaUsuario extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaUsuario.class.getName());
    private HelpBroker hb;
    private int idUsuario;
    String nombreUsuario;
    public int idIncidencia;

    /**
     * Creates new form VistaUsuario
     */
    public VistaUsuario(int idUsuario, String nombreUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jLabel3.setText("Buenas, " + nombreUsuario + " ¿Que necesitas?");
        this.idUsuario = idUsuario;
        refrescarTabla();
        inicializarAyuda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jButtonCrearIndicencia = new javax.swing.JButton();
        jButtonListarIncidenciaId = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonReapertura = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonListarIndicencias = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        jSpinnerListarIncidenciaId = new javax.swing.JSpinner();
        jSpinnerSolicitarReaperturaid = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Buenas, ¿Que necesitas?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Incidencia", "estado", "result_cierre", "f_cierre", "f_entrada", "tipo_incidencia", "ID_Usuario", "ID_Tecnico", "Descripcion", "Solucion", "Prioridad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsuario);
        if (jTableUsuario.getColumnModel().getColumnCount() > 0) {
            jTableUsuario.getColumnModel().getColumn(0).setResizable(false);
            jTableUsuario.getColumnModel().getColumn(1).setResizable(false);
            jTableUsuario.getColumnModel().getColumn(2).setResizable(false);
            jTableUsuario.getColumnModel().getColumn(3).setResizable(false);
            jTableUsuario.getColumnModel().getColumn(4).setResizable(false);
            jTableUsuario.getColumnModel().getColumn(5).setResizable(false);
            jTableUsuario.getColumnModel().getColumn(6).setResizable(false);
            jTableUsuario.getColumnModel().getColumn(7).setResizable(false);
        }

        jButtonCrearIndicencia.setText("Crear Incidencia");
        jButtonCrearIndicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearIndicenciaActionPerformed(evt);
            }
        });

        jButtonListarIncidenciaId.setText("Listar Incidencia por ID");
        jButtonListarIncidenciaId.setActionCommand("Listar Incidencias");
        jButtonListarIncidenciaId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarIncidenciaIdActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jButtonReapertura.setText("Solicitar reapertura");
        jButtonReapertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReaperturaActionPerformed(evt);
            }
        });

        jButtonSalir.setBackground(new java.awt.Color(255, 102, 102));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonListarIndicencias.setText("Listar Indicencias");
        jButtonListarIndicencias.setActionCommand("ListarIndicencias");
        jButtonListarIndicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarIndicenciasActionPerformed(evt);
            }
        });

        jButtonCerrarSesion.setText("Cerrar Sesion");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jMenu1.setText("Ayuda");

        jMenuItemAyuda.setText("Abrir ayuda");
        jMenuItemAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemAyudaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemAyudaMousePressed(evt);
            }
        });
        jMenuItemAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAyudaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAyuda);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinnerSolicitarReaperturaid, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)
                                .addGap(7, 7, 7)
                                .addComponent(jButtonReapertura, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinnerListarIncidenciaId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel1)
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonListarIndicencias)
                                    .addComponent(jButtonListarIncidenciaId)
                                    .addComponent(jButtonCrearIndicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSalir)
                        .addGap(6, 6, 6)
                        .addComponent(jButtonCerrarSesion))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButtonCrearIndicencia)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerListarIncidenciaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1))
                            .addComponent(jButtonListarIncidenciaId))
                        .addGap(6, 6, 6)
                        .addComponent(jButtonListarIndicencias)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerSolicitarReaperturaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2))
                            .addComponent(jButtonReapertura))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonCerrarSesion))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearIndicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearIndicenciaActionPerformed
        JDialogCrearIncidencia dCrearIncidencia = new JDialogCrearIncidencia(this, true, idUsuario);
        dCrearIncidencia.setVisible(true);
    }//GEN-LAST:event_jButtonCrearIndicenciaActionPerformed

    private void jButtonListarIncidenciaIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarIncidenciaIdActionPerformed
        // TODO add your handling code here:
        try {
            refrescarTablaPorID((int) this.jSpinnerListarIncidenciaId.getValue());
        } catch (Exception e) {
            System.out.println("Ingrese un numero entero en el campo ID");
        }

    }//GEN-LAST:event_jButtonListarIncidenciaIdActionPerformed

    private void jButtonReaperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReaperturaActionPerformed
        try {

            udi.solicitarReapertura((int) this.jSpinnerSolicitarReaperturaid.getValue());
            refrescarTabla();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonReaperturaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonListarIndicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarIndicenciasActionPerformed
        // TODO add your handling code here:
        refrescarTabla();
    }//GEN-LAST:event_jButtonListarIndicenciasActionPerformed

    private void jTableUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuarioMouseClicked
        int fila = this.jTableUsuario.rowAtPoint(evt.getPoint());
        String estado = "";
        idIncidencia = (int) this.jTableUsuario.getValueAt(fila, 0);
        try {
            estado = this.jTableUsuario.getValueAt(fila, 1).toString();
            this.jSpinnerListarIncidenciaId.setValue(idIncidencia);
            if (estado.equals("cerrada")) {
                this.jSpinnerSolicitarReaperturaid.setValue(idIncidencia);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jTableUsuarioMouseClicked

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        JFrameLogin login = new JFrameLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void jMenuItemAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAyudaActionPerformed
        ponLaAyuda();    }//GEN-LAST:event_jMenuItemAyudaActionPerformed

    private void jMenuItemAyudaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAyudaMousePressed
        ponLaAyuda();    }//GEN-LAST:event_jMenuItemAyudaMousePressed

    private void jMenuItemAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAyudaMouseClicked
        ponLaAyuda();    }//GEN-LAST:event_jMenuItemAyudaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonCrearIndicencia;
    private javax.swing.JButton jButtonListarIncidenciaId;
    private javax.swing.JButton jButtonListarIndicencias;
    private javax.swing.JButton jButtonReapertura;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAyuda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerListarIncidenciaId;
    private javax.swing.JSpinner jSpinnerSolicitarReaperturaid;
    private javax.swing.JTable jTableUsuario;
    // End of variables declaration//GEN-END:variables

    protected UsuarioDAOimpl udi = new UsuarioDAOimpl();

    public void refrescarTabla() {
        DefaultTableModel m = (DefaultTableModel) this.jTableUsuario.getModel();
        m.setNumRows(0);

        Incidencia i = null;
        try {
            ArrayList<Incidencia> ai = (ArrayList<Incidencia>) udi.getIncidenciasUsuario(idUsuario);
            for (int j = 0; j < ai.size(); j++) {
                i = ai.get(j);
                Object[] o = {
                    i.getIdIncidencia(),
                    i.getEstado(),
                    i.getResultado_cierre(),
                    i.getFechaCierre(),
                    i.getFechaEntrada(),
                    i.getTipoIncidencia(),
                    i.getIdUsuario(),
                    i.getIdTecnico(),
                    i.getDescripcionIncidencia(),
                    i.getDescripcionSolucion(),
                    i.getPrioridad()

                };
                m.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar tabla incidencia");
            e.printStackTrace();
        }
    }

    public void refrescarTablaPorID(int id) {
        DefaultTableModel m = (DefaultTableModel) this.jTableUsuario.getModel();
        m.setNumRows(0);

        try {
            Incidencia i = udi.getIncidenciaPorId(id, this.idUsuario);

            //i = udi.getIncidenciaPorId(id);
            Object[] o = {
                i.getIdIncidencia(),
                i.getEstado(),
                i.getResultado_cierre(),
                i.getFechaCierre(),
                i.getFechaEntrada(),
                i.getTipoIncidencia(),
                i.getIdUsuario(),
                i.getIdTecnico(),
                i.getDescripcionIncidencia(),
                i.getDescripcionSolucion(),
                i.getPrioridad()

            };

            m.addRow(o);
        } catch (Exception ex) {
            System.out.println("Error al cargar la tabla por id" + ex.getMessage());
        }
    }

    private void ponLaAyuda() {
        hb.enableHelpOnButton(jMenuItemAyuda, "usuario", null);
        hb.enableHelpKey(getRootPane(), "usuario", null);
    }

    private void inicializarAyuda() {
        try {
            File fichero = new File("help" + File.separator + "helpset.hs");
            URL hsURL = fichero.toURI().toURL();

            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            hb = helpset.createHelpBroker();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
