/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.com.tic.exec.gestor;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import src.com.tic.dao.GestorDAOimpl;
import src.com.tic.dao.TecnicoDAOimpl;
import src.com.tic.exec.JFrameLogin;
import src.com.tic.pojo.Incidencia;
import src.com.tic.pojo.Usuario;

/**
 *
 * @author alumno
 */
public class VistaGestor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaGestor.class.getName());
    GestorDAOimpl gestorDAO = new GestorDAOimpl();
    private int idUsuario;
    private int idTecnico;
    private int idIncidencia;

    /**
     * Creates new form VistaGestor
     */
    public VistaGestor(int idUsuario, String usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jLabel3.setText("¡¡¡Hola, " + usuario + ". A atender se ha dicho!!!");
        this.idUsuario = idUsuario;
        refrescarTablaIncidenciasEspera();
        refrescarTablaTecnicosDisp();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGestor = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAsignarTecnico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonPonerEspera = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonListarIndicendiaEspera = new javax.swing.JButton();
        jButtonListarTipoIncidencias = new javax.swing.JButton();
        jSpinnerIdTecnicoAsignar = new javax.swing.JSpinner();
        jSpinnerIdIncidenciaAsignar = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jButtonListarTodas = new javax.swing.JButton();
        jButtonSalir1 = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("¡¡¡A atender se ha dicho!!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(jLabel3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3))
        );

        jTableGestor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Incidencia", "estado", "result_cierre", "f_cierre", "f_entrada", "tipo_incidencia", "ID_Usuario", "ID_Tecnico", "Descripcion", "Solucion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableGestor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGestorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableGestor);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Tecnico", "ID_Usuario", "nombre", "apellidos", "correo", "telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButtonAsignarTecnico.setText("Asignar Tecnico");
        jButtonAsignarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarTecnicoActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Incidencia");

        jLabel2.setText("ID Tecnico");

        jButtonPonerEspera.setText("Poner en Espera");
        jButtonPonerEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPonerEsperaActionPerformed(evt);
            }
        });

        jLabel4.setText("ID Indicencia");

        jButtonListarIndicendiaEspera.setText("Listar Incidencia en Espera");
        jButtonListarIndicendiaEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarIndicendiaEsperaActionPerformed(evt);
            }
        });

        jButtonListarTipoIncidencias.setText("Listar por tipo de Incidencia y por ID Tecnico");
        jButtonListarTipoIncidencias.setToolTipText("");
        jButtonListarTipoIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarTipoIncidenciasActionPerformed(evt);
            }
        });

        jButtonListarTodas.setText("Listar todas");

        jButtonSalir1.setText("Salir");
        jButtonSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalir1ActionPerformed(evt);
            }
        });

        jButtonCerrarSesion.setText("Cerrar Sesion");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerIdIncidenciaAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinnerIdTecnicoAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(92, 92, 92)
                                        .addComponent(jButtonListarIndicendiaEspera)
                                        .addGap(37, 37, 37)
                                        .addComponent(jButtonListarTodas))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(jButtonAsignarTecnico)
                                        .addGap(185, 185, 185)
                                        .addComponent(jButtonPonerEspera)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonCerrarSesion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonSalir1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jButtonListarTipoIncidencias, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinnerIdIncidenciaAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinnerIdTecnicoAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListarIndicendiaEspera)
                    .addComponent(jButtonListarTodas)
                    .addComponent(jButtonListarTipoIncidencias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAsignarTecnico)
                        .addComponent(jButtonPonerEspera))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSalir1)
                        .addComponent(jButtonCerrarSesion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPonerEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPonerEsperaActionPerformed
        try {
            gestorDAO.ponerEnEspera((int)this.jSpinner3.getValue());
        } catch (Exception ex) {
            System.out.println("Error al poner en espera: " + ex.getMessage());
        }
        refrescarTablaIncidenciasEspera();
        refrescarTablaTecnicosDisp();
    }//GEN-LAST:event_jButtonPonerEsperaActionPerformed

    private void jButtonListarIndicendiaEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarIndicendiaEsperaActionPerformed
        refrescarTablaIncidenciasEspera();
    }//GEN-LAST:event_jButtonListarIndicendiaEsperaActionPerformed

    private void jButtonListarTipoIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarTipoIncidenciasActionPerformed
        jDialogTipoIncidenciaTecnico dTipoIncidenciaTecnico = new jDialogTipoIncidenciaTecnico(this, true);
        dTipoIncidenciaTecnico.setVisible(true);
    }//GEN-LAST:event_jButtonListarTipoIncidenciasActionPerformed

    private void jButtonAsignarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarTecnicoActionPerformed
        try {
            gestorDAO.asignarTecnico((int)this.jSpinnerIdTecnicoAsignar.getValue(), (int)this.jSpinnerIdIncidenciaAsignar.getValue());
        } catch (Exception ex) {
            System.out.println("Error al asignar técnico:" + ex.getMessage());
        }
        refrescarTablaIncidenciasEspera();
        refrescarTablaTecnicosDisp();
    }//GEN-LAST:event_jButtonAsignarTecnicoActionPerformed

    private void jTableGestorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGestorMouseClicked
        int fila = this.jTableGestor.rowAtPoint(evt.getPoint());
        this.idIncidencia = (int) this.jTableGestor.getValueAt(fila, 0);
        this.jSpinnerIdIncidenciaAsignar.setValue(this.jTableGestor.getValueAt(fila, 0));
        this.jSpinner3.setValue(this.jTableGestor.getValueAt(fila,0));
    }//GEN-LAST:event_jTableGestorMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = this.jTable1.rowAtPoint(evt.getPoint());
        this.idTecnico = (int) this.jTable1.getValueAt(fila, 0);
        this.jSpinnerIdTecnicoAsignar.setValue(this.jTable1.getValueAt(fila, 0));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalir1ActionPerformed

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        JFrameLogin login = new JFrameLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

//    private void refrescarTablaIncidencias() {
//        DefaultTableModel m = (DefaultTableModel) this.jTableGestor.getModel();
//        m.setNumRows(0);
//
//        Incidencia i = null;
//        try {
//            ArrayList<Incidencia> ai = (ArrayList<Incidencia>) gestorDAO.getAllIncidencias();
//            for (int j = 0; j < ai.size(); j++) {
//                i = ai.get(j);
//                Object[] o = {
//                    i.getIdIncidencia(),
//                    i.getEstado(),
//                    i.getResultado_cierre(),
//                    i.getFechaCierre(),
//                    i.getFechaEntrada(),
//                    i.getTipoIncidencia(),
//                    i.getIdUsuario(),
//                    i.getIdTecnico(),
//                    i.getDescripcionIncidencia(),
//                    i.getDescripcionSolucion()
//                };
//                m.addRow(o);
//            }
//        } catch (Exception e) {
//            System.out.println("Error al mostrar tabla incidencia");
//        }
//    }
    private void refrescarTablaTecnicosDisp() {
        DefaultTableModel m = (DefaultTableModel) this.jTable1.getModel();
        m.setNumRows(0);

        Incidencia i = null;
        try {
            ArrayList<Integer> ai = (ArrayList<Integer>) gestorDAO.getTecnicoDisp();
            for (Integer integer : ai) {
                Usuario user = gestorDAO.getTecnicoById(integer);
                Object[] o = {
                    integer,
                    user.getIdUsuario(),
                    user.getNombreDeUsuario(),
                    user.getNombreApellidos(),
                    user.getCorreo(),
                    user.getNumeroTelefono()
                };
                m.addRow(o);
            }

        } catch (Exception e) {
            System.out.println("Error al mostrar tabla incidencia" + e.getMessage());
        }
    }

    private void refrescarTablaIncidenciasEspera() {
        DefaultTableModel m = (DefaultTableModel) this.jTableGestor.getModel();
        m.setNumRows(0);

        Incidencia i = null;
        try {
            ArrayList<Incidencia> ai = (ArrayList<Incidencia>) gestorDAO.getIncidenciasByEspera();
            for (int j = 0; j < ai.size(); j++) {
                i = ai.get(j);
                System.out.println(i);
                Object[] o = {
                    i.getIdIncidencia(),
                    i.getEstado(),
                    i.getResultado_cierre(),
                    i.getFechaCierre(),
                    i.getFechaEntrada(),
                    i.getTipoIncidencia(),
                    i.getIdUsuario(),
                    i.getIdTecnico(),
                    i.getDescripcionIncidencia(),
                    i.getDescripcionSolucion()
                };
                m.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar tabla incidencia");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAsignarTecnico;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonListarIndicendiaEspera;
    private javax.swing.JButton jButtonListarTipoIncidencias;
    private javax.swing.JButton jButtonListarTodas;
    private javax.swing.JButton jButtonPonerEspera;
    private javax.swing.JButton jButtonSalir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinnerIdIncidenciaAsignar;
    private javax.swing.JSpinner jSpinnerIdTecnicoAsignar;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableGestor;
    // End of variables declaration//GEN-END:variables
}
