package src.com.tic.exec;

import java.io.File;
import java.net.URL;
import java.util.Arrays;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.swing.JOptionPane;
import src.com.tic.dao.LoginDAOimpl;
import src.com.tic.exec.Administrador.VistaAdministrador;
import src.com.tic.exec.Tecnico.VistaTecnico;
import src.com.tic.exec.Usuario.VistaUsuario;
import src.com.tic.exec.gestor.VistaGestor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author tarde
 */
public class JFrameLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameLogin.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public JFrameLogin() {
        initComponents();
        this.setSize(500, 400);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldContrasena = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemAyuda = new javax.swing.JMenuItem();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(this::jButtonLoginActionPerformed);
        getContentPane().add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, 30));

        jTextFieldUsuario.addActionListener(this::jTextFieldUsuarioActionPerformed);
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 183, 30));

        jPasswordFieldContrasena.addActionListener(this::jPasswordFieldContrasenaActionPerformed);
        getContentPane().add(jPasswordFieldContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 183, 30));

        jLabel1.setText("Tipo de cuenta:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, 20));

        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Gestor", "Técnico", "Administrador" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, 30));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 20));

        jMenuAyuda.setText("Ayuda");
        jMenuAyuda.addActionListener(this::jMenuAyudaActionPerformed);

        jMenuItemAyuda.setText("Abrir ayuda");
        jMenuItemAyuda.addActionListener(this::jMenuItemAyudaActionPerformed);
        jMenuAyuda.add(jMenuItemAyuda);

        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String hash = new String(jPasswordFieldContrasena.getPassword());
        String usuario = jTextFieldUsuario.getText();
        int idUsuario;
        try {
            idUsuario = limpl.compararContraseña(hash, usuario);
            System.out.println(idUsuario);
            if (idUsuario == -1) {
                this.jTextFieldUsuario.setText("");
                this.jPasswordFieldContrasena.setText("");
                JOptionPane.showMessageDialog(null, "El usuario introducido no existe o la contraseña es incorrecta.", "CREEDENCIALES INCORRECTAS", JOptionPane.ERROR_MESSAGE);

            } else {
                if (this.jComboBox1.getSelectedItem().toString().equals("Usuario")) {
                    //Metodo para ver si hay un Usuario con esa Id
                    VistaUsuario vistaUs = new VistaUsuario(idUsuario, usuario);
                    vistaUs.setVisible(true);
                    dispose();

                } else if (this.jComboBox1.getSelectedItem().toString().equals("Gestor")) {
                    //Metodo para ver si hay un Gestor con esa Id
                    if (limpl.esGestor(idUsuario)) {
                        VistaGestor vistaGes = new VistaGestor(idUsuario, usuario);
                        vistaGes.setVisible(true);
                        dispose();
                    } else {
                        this.jTextFieldUsuario.setText("");
                        this.jPasswordFieldContrasena.setText("");
                        JOptionPane.showMessageDialog(null, "El usuario introducido no es un gestor", "ROL INCORRECTO", JOptionPane.ERROR_MESSAGE);

                    }
                } else if (this.jComboBox1.getSelectedItem().toString().equals("Técnico")) {
                    //Metodo para ver si hay un Tecnico con esa Id
                    if (limpl.esTecnico(idUsuario)) {
                        VistaTecnico vistaTec = new VistaTecnico(idUsuario, usuario);
                        vistaTec.setVisible(true);
                        dispose();
                    } else {
                        this.jTextFieldUsuario.setText("");
                        this.jPasswordFieldContrasena.setText("");
                        JOptionPane.showMessageDialog(null, "El usuario introducido no es un técnico", "ROL INCORRECTO", JOptionPane.ERROR_MESSAGE);
                    }
                } else if (this.jComboBox1.getSelectedItem().toString().equals("Administrador")) {
                    //Metodo para ver si hay un Admin con esa Id
                    if (limpl.esAdministrador(idUsuario)) {
                        VistaAdministrador vistaAdm = new VistaAdministrador(idUsuario);
                        vistaAdm.setVisible(true);
                        dispose();
                    } else {
                        this.jTextFieldUsuario.setText("");
                        this.jPasswordFieldContrasena.setText("");
                        JOptionPane.showMessageDialog(null, "El usuario introducido no es un administrador", "ROL INCORRECTO", JOptionPane.ERROR_MESSAGE);

                    }

                }
            }

        } catch (Exception ex) {
            System.out.println("Error de login: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jPasswordFieldContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldContrasenaActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jMenuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAyudaActionPerformed

    private void jMenuItemAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAyudaActionPerformed
        ponLaAyuda();
    }//GEN-LAST:event_jMenuItemAyudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameLogin().setVisible(true));
    }
    private LoginDAOimpl limpl = new LoginDAOimpl();

    private void ponLaAyuda() {
        try {
            //Carga el fichero de ayuda
            File fichero = new File("help" + File.separator + "helpset.hs");
            URL hsURL = fichero.toURI().toURL();

            //Crea el HelpSet y el HelpBroker
            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            HelpBroker hb = helpset.createHelpBroker();

            hb.enableHelpOnButton(jMenuItemAyuda, "login", helpset);
            hb.enableHelpKey(getRootPane(), "login", helpset);
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Error al cargar la ayuda: " + e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAyuda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldContrasena;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
