/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.com.tic.exec.Administrador;

/**
 *
 * @author yuta
 */
public class JFrameGestionarEspacio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameGestionarEspacio.class.getName());

    /**
     * Creates new form JFrameGestionarUsuario
     */
    public JFrameGestionarEspacio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEspacio = new javax.swing.JTable();
        jButtonListadoCompleto = new javax.swing.JButton();
        jSpinnerIDEspacio = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonEliminarEspacio = new javax.swing.JButton();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonActualizarEspacio = new javax.swing.JButton();
        jButtonRegistrarNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestionar Espacio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 70));

        jTableEspacio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Espacio", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableEspacio);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 510, 300));

        jButtonListadoCompleto.setText("Listado competo");
        jButtonListadoCompleto.addActionListener(this::jButtonListadoCompletoActionPerformed);
        getContentPane().add(jButtonListadoCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 150, 40));
        getContentPane().add(jSpinnerIDEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 100, 30));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEliminarEspacio.setBackground(new java.awt.Color(204, 0, 0));
        jButtonEliminarEspacio.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonEliminarEspacio.setText("Eliminar Espacio");
        jButtonEliminarEspacio.addActionListener(this::jButtonEliminarEspacioActionPerformed);
        jPanel2.add(jButtonEliminarEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 174, 50));
        jPanel2.add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 150, 40));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Descripción:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButtonActualizarEspacio.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonActualizarEspacio.setText("Actualizar Espacio");
        jButtonActualizarEspacio.addActionListener(this::jButtonActualizarEspacioActionPerformed);
        jPanel2.add(jButtonActualizarEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 50));

        jButtonRegistrarNuevo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonRegistrarNuevo.setText("Registrar Nuevo");
        jPanel2.add(jButtonRegistrarNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 174, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 380, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListadoCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListadoCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonListadoCompletoActionPerformed

    private void jButtonActualizarEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarEspacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizarEspacioActionPerformed

    private void jButtonEliminarEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarEspacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarEspacioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameGestionarEspacio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizarEspacio;
    private javax.swing.JButton jButtonEliminarEspacio;
    private javax.swing.JButton jButtonListadoCompleto;
    private javax.swing.JButton jButtonRegistrarNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerIDEspacio;
    private javax.swing.JTable jTableEspacio;
    private javax.swing.JTextField jTextFieldDescripcion;
    // End of variables declaration//GEN-END:variables
}
