/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.com.tic.exec.Administrador;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import src.com.tic.dao.AdministradorDAOimpl;
import src.com.tic.pojo.Dispositivo;
import src.com.tic.pojo.Espacio;

/**
 *
 * @author yuta
 */
public class JFrameGestionarEspacio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameGestionarEspacio.class.getName());
    AdministradorDAOimpl adminDAO = new AdministradorDAOimpl();

    /**
     * Creates new form JFrameGestionarUsuario
     */
    public JFrameGestionarEspacio() {
        initComponents();
        refrescarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEspacio = new javax.swing.JTable();
        jSpinnerIDEspacio = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonEliminarEspacio = new javax.swing.JButton();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonActualizarEspacio = new javax.swing.JButton();
        jButtonRegistrarNuevo = new javax.swing.JButton();
        jButtonListarVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestionar Espacio");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTableEspacio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Espacio", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEspacio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEspacioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableEspacio);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("ID:");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEliminarEspacio.setBackground(new java.awt.Color(204, 0, 0));
        jButtonEliminarEspacio.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonEliminarEspacio.setText("Eliminar Espacio");
        jButtonEliminarEspacio.addActionListener(this::jButtonEliminarEspacioActionPerformed);
        jPanel2.add(jButtonEliminarEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 174, 50));
        jPanel2.add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 340, 30));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Descripción:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButtonActualizarEspacio.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonActualizarEspacio.setText("Actualizar Espacio");
        jButtonActualizarEspacio.addActionListener(this::jButtonActualizarEspacioActionPerformed);
        jPanel2.add(jButtonActualizarEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 50));

        jButtonRegistrarNuevo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonRegistrarNuevo.setText("Registrar Nuevo");
        jButtonRegistrarNuevo.addActionListener(this::jButtonRegistrarNuevoActionPerformed);
        jPanel2.add(jButtonRegistrarNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 174, 50));

        jButtonListarVolver.setText("Volver");
        jButtonListarVolver.addActionListener(this::jButtonListarVolverActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonListarVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel1)
                                .addGap(14, 14, 14)
                                .addComponent(jSpinnerIDEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jSpinnerIDEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonListarVolver)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActualizarEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarEspacioActionPerformed
        try {
            if (this.jTextFieldDescripcion.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Rellena los campos vacios", "CAMPO VACIO", JOptionPane.ERROR_MESSAGE);
            }
            adminDAO.updateEspacio(new Espacio((int) this.jSpinnerIDEspacio.getValue(), this.jTextFieldDescripcion.getText()));
            refrescarTabla();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //Aqui necesitamos un control de errores para que primero llene todos los campos obligatoriamente
    }//GEN-LAST:event_jButtonActualizarEspacioActionPerformed

    private void jButtonEliminarEspacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarEspacioActionPerformed
        try {
            if ((int) this.jSpinnerIDEspacio.getValue() == 0) {
                JOptionPane.showMessageDialog(null, "Selecciona un id", "ID INVALIDO", JOptionPane.ERROR_MESSAGE);
            } else {
                adminDAO.deleteEspacio((int) this.jSpinnerIDEspacio.getValue());
                refrescarTabla();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //Aqui necesitamos que la ID exista
    }//GEN-LAST:event_jButtonEliminarEspacioActionPerformed

    private void jButtonListarVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarVolverActionPerformed
        VistaAdministrador atras = new VistaAdministrador();
        atras.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonListarVolverActionPerformed

    private void jTableEspacioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEspacioMouseClicked
        int fila = this.jTableEspacio.rowAtPoint(evt.getPoint());
        this.jSpinnerIDEspacio.setValue((int) this.jTableEspacio.getValueAt(fila, 0));
        this.jTextFieldDescripcion.setText((String) this.jTableEspacio.getValueAt(fila, 1));

    }//GEN-LAST:event_jTableEspacioMouseClicked

    private void jButtonRegistrarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarNuevoActionPerformed
        try {
            if (this.jTextFieldDescripcion.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Rellena los campos vacios", "CAMPO VACIO", JOptionPane.ERROR_MESSAGE);
            } else {
                adminDAO.insertEspacios(new Espacio((int) this.jSpinnerIDEspacio.getValue(), this.jTextFieldDescripcion.getText()));
                refrescarTabla();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        //Obligatorio que rellene los campos
    }//GEN-LAST:event_jButtonRegistrarNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new JFrameGestionarEspacio().setVisible(true));
    }

    public void refrescarTabla() {
        DefaultTableModel m = (DefaultTableModel) this.jTableEspacio.getModel();
        m.setNumRows(0);

        Espacio i = null;
        try {
            ArrayList<Espacio> ai = (ArrayList<Espacio>) adminDAO.getEspacios();
            for (int j = 0; j < ai.size(); j++) {
                i = ai.get(j);
                Object[] o = {
                    i.getIdEspacio(),
                    i.getDescripcion()
                };
                m.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar tabla incidencia");
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizarEspacio;
    private javax.swing.JButton jButtonEliminarEspacio;
    private javax.swing.JButton jButtonListarVolver;
    private javax.swing.JButton jButtonRegistrarNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerIDEspacio;
    private javax.swing.JTable jTableEspacio;
    private javax.swing.JTextField jTextFieldDescripcion;
    // End of variables declaration//GEN-END:variables
}
