/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.com.tic.exec.Administrador;

/**
 *
 * @author yuta
 */
public class JFrameGestionarIncidencia extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameGestionarIncidencia.class.getName());

    /**
     * Creates new form JFrameGestionarUsuario
     */
    public JFrameGestionarIncidencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableIncidencia = new javax.swing.JTable();
        jButtonListarVolver = new javax.swing.JButton();
        jButtonListarTipo = new javax.swing.JButton();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jSpinnerIDIncidencia = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonEliminar = new javax.swing.JButton();
        jTextFieldFEntrada = new javax.swing.JTextField();
        jTextFieldFCierre = new javax.swing.JTextField();
        jTextFieldRCierre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonActualizar = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jTextFieldTipo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldSolucion = new javax.swing.JTextField();
        jButtonListarCompleto = new javax.swing.JButton();
        jSpinnerIDUsuario = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jSpinnerIDTecnico = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestionar Incidencia");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 70));

        jTableIncidencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Incidencia", "Estado", "Resultado cierre", "Fecha Cierre", "Fecha Entrada", "Tipo", "ID Usuario", "ID Tecnico", "Descripcion", "Solucion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableIncidencia);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 510, 300));

        jButtonListarVolver.setText("Volver");
        jButtonListarVolver.addActionListener(this::jButtonListarVolverActionPerformed);
        getContentPane().add(jButtonListarVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 150, 40));

        jButtonListarTipo.setText("Listado por tipo:");
        getContentPane().add(jButtonListarTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 140, 40));

        jComboBoxTipo.addActionListener(this::jComboBoxTipoActionPerformed);
        getContentPane().add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 140, 40));
        getContentPane().add(jSpinnerIDIncidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 100, 30));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("ID Incidenia:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEliminar.setBackground(new java.awt.Color(204, 0, 0));
        jButtonEliminar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jPanel2.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 160, 50));
        jPanel2.add(jTextFieldFEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 248, 150, 40));
        jPanel2.add(jTextFieldFCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 178, 150, 40));
        jPanel2.add(jTextFieldRCierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 108, 150, 40));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Resultado Cierre:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 78, -1, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setText("Fecha Cierre:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 148, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setText("Fecha Entrada:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 218, -1, -1));

        jTextFieldEstado.addActionListener(this::jTextFieldEstadoActionPerformed);
        jPanel2.add(jTextFieldEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 38, 150, 40));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Estado:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, -1, -1));

        jButtonActualizar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonActualizar.setText("Actualizar ");
        jButtonActualizar.setActionCommand("Actualizar ");
        jButtonActualizar.addActionListener(this::jButtonActualizarActionPerformed);
        jPanel2.add(jButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 160, 50));

        jButtonRegistrar.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonRegistrar.setText("Registrar Nuevo");
        jPanel2.add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 160, 50));
        jPanel2.add(jTextFieldTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 150, 40));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setText("Tipo:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setText("Descripcion:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));
        jPanel2.add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 150, 40));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setText("Solucion:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));
        jPanel2.add(jTextFieldSolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 150, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 520, 370));

        jButtonListarCompleto.setText("Listado competo");
        jButtonListarCompleto.addActionListener(this::jButtonListarCompletoActionPerformed);
        getContentPane().add(jButtonListarCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 150, 40));
        getContentPane().add(jSpinnerIDUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, 100, 30));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel10.setText("ID Usuario:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, -1, -1));
        getContentPane().add(jSpinnerIDTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 80, 100, 30));

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel11.setText("ID Tecnico:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListarVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonListarVolverActionPerformed

    private void jTextFieldEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstadoActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jButtonListarCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonListarCompletoActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameGestionarIncidencia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonListarCompleto;
    private javax.swing.JButton jButtonListarTipo;
    private javax.swing.JButton jButtonListarVolver;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerIDIncidencia;
    private javax.swing.JSpinner jSpinnerIDTecnico;
    private javax.swing.JSpinner jSpinnerIDUsuario;
    private javax.swing.JTable jTableIncidencia;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldFCierre;
    private javax.swing.JTextField jTextFieldFEntrada;
    private javax.swing.JTextField jTextFieldRCierre;
    private javax.swing.JTextField jTextFieldSolucion;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
