package src.com.tic.exec.Administrador;

import java.awt.event.ItemEvent;
import java.util.Arrays;
import javax.swing.JOptionPane;
import src.com.tic.dao.AdministradorDAOimpl;
import src.com.tic.pojo.Usuario;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author tarde
 */
public class JFrameRegister extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameRegister.class.getName());
    private boolean esGestor = false;
    private boolean esTecnico = false;
    private boolean esAdmin = false;
    AdministradorDAOimpl aimpl = new AdministradorDAOimpl();

    /**
     * Creates new form NewJFrame
     */
    public JFrameRegister() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jTextFieldNombreApellidos = new javax.swing.JTextField();
        jPasswordFieldContrasena = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordFieldRepetirContrasena = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        checkboxGestor = new java.awt.Checkbox();
        checkboxTecnico = new java.awt.Checkbox();
        checkboxAdmin = new java.awt.Checkbox();
        jButtonListarVolver = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 535));
        setPreferredSize(new java.awt.Dimension(550, 535));
        setSize(new java.awt.Dimension(550, 535));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonRegister.setText("Crear cuenta");
        jButtonRegister.addActionListener(this::jButtonRegisterActionPerformed);
        getContentPane().add(jButtonRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 150, 30));

        jTextFieldNombreApellidos.addActionListener(this::jTextFieldNombreApellidosActionPerformed);
        getContentPane().add(jTextFieldNombreApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 183, 30));

        jPasswordFieldContrasena.addActionListener(this::jPasswordFieldContrasenaActionPerformed);
        getContentPane().add(jPasswordFieldContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 183, 30));

        jLabel1.setText("Contraseña:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, 20));

        jLabel2.setText("Usuario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 20));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registrar nuevo usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        jPasswordFieldRepetirContrasena.addActionListener(this::jPasswordFieldRepetirContrasenaActionPerformed);
        getContentPane().add(jPasswordFieldRepetirContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 183, 30));

        jLabel4.setText("Confirmar contraseña:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, 20));

        jLabel5.setText("Tipo de cuenta:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, 20));

        jTextFieldCorreo.addActionListener(this::jTextFieldCorreoActionPerformed);
        getContentPane().add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 183, 30));

        jLabel6.setText("Correo electrónico:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, 20));

        jTextFieldTelefono.addActionListener(this::jTextFieldTelefonoActionPerformed);
        getContentPane().add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 183, 30));

        jLabel7.setText("Número de telefono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, 20));

        jLabel8.setText("Nombre y apellidos:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 20));

        jTextFieldUsuario.addActionListener(this::jTextFieldUsuarioActionPerformed);
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 183, 30));

        checkboxGestor.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        checkboxGestor.setLabel("Es Gestor");
        checkboxGestor.addItemListener(this::checkboxGestorItemStateChanged);
        getContentPane().add(checkboxGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));

        checkboxTecnico.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        checkboxTecnico.setLabel("Es Técnico");
        checkboxTecnico.addItemListener(this::checkboxTecnicoItemStateChanged);
        getContentPane().add(checkboxTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        checkboxAdmin.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        checkboxAdmin.setLabel("Es Admin");
        checkboxAdmin.addItemListener(this::checkboxAdminItemStateChanged);
        getContentPane().add(checkboxAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        jButtonListarVolver.setText("Volver");
        jButtonListarVolver.addActionListener(this::jButtonListarVolverActionPerformed);
        getContentPane().add(jButtonListarVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        if (Arrays.equals(this.jPasswordFieldContrasena.getPassword(), this.jPasswordFieldRepetirContrasena.getPassword())) {
            try {
                if (this.jTextFieldNombreApellidos.getText().equals("") || this.jTextFieldUsuario.getText().equals("")
                        || this.jTextFieldCorreo.getText().equals("") || this.jTextFieldTelefono.getText().equals("")
                        || this.jPasswordFieldContrasena.getPassword().equals("") || this.jPasswordFieldRepetirContrasena.getPassword().equals("")) {
                    JOptionPane.showMessageDialog(null, "Rellene todos los campos", "CAMPO VACIO", JOptionPane.ERROR_MESSAGE);
                } else {
                    Usuario usuario = new Usuario(this.jTextFieldUsuario.getText(), this.jTextFieldNombreApellidos.getText(), this.jTextFieldCorreo.getText(), this.jTextFieldTelefono.getText(), new String(this.jPasswordFieldContrasena.getPassword()));
                    int idUsuario = this.aimpl.crearUsuario(usuario);
                    if (esTecnico) {
                        this.aimpl.hacerTecnico(idUsuario);
                    }
                    if (esAdmin) {
                        this.aimpl.hacerAdmin(idUsuario);
                    } else if (esGestor) {
                        this.aimpl.hacerGestor(idUsuario);
                    }
                    JOptionPane.showMessageDialog(null, "Se ha introducido el usuario " + usuario.getNombreDeUsuario() + " con éxito", "USUARIO INTRODUCIDO CON ÉXITO", JOptionPane.OK_OPTION);
                    this.jTextFieldUsuario.setText("");
                    this.jTextFieldCorreo.setText("");
                    this.jTextFieldTelefono.setText("");
                    this.jTextFieldNombreApellidos.setText("");
                    this.jPasswordFieldContrasena.setText("");
                    this.jPasswordFieldRepetirContrasena.setText("");

                }
            } catch (Exception ex) {
                System.out.println("Error de sql: " + ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "La contraseña no coincide con el campo de confirmación", "CONTRASEÑA NO COINCIDE", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jPasswordFieldContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldContrasenaActionPerformed

    private void jTextFieldNombreApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreApellidosActionPerformed

    private void jPasswordFieldRepetirContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldRepetirContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldRepetirContrasenaActionPerformed

    private void jTextFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void checkboxGestorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxGestorItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.esGestor = true;
        } else {
            this.esGestor = false;
        }
    }//GEN-LAST:event_checkboxGestorItemStateChanged

    private void checkboxTecnicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxTecnicoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.esTecnico = true;
        } else {
            this.esTecnico = false;
        }
    }//GEN-LAST:event_checkboxTecnicoItemStateChanged

    private void checkboxAdminItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkboxAdminItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            this.esGestor = true;
            checkboxGestor.setState(true);
            this.esAdmin = true;
        } else {
            this.esAdmin = false;
        }
    }//GEN-LAST:event_checkboxAdminItemStateChanged

    private void jButtonListarVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarVolverActionPerformed
        VistaAdministrador atras = new VistaAdministrador();
        atras.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonListarVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameRegister().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkboxAdmin;
    private java.awt.Checkbox checkboxGestor;
    private java.awt.Checkbox checkboxTecnico;
    private javax.swing.JButton jButtonListarVolver;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldContrasena;
    private javax.swing.JPasswordField jPasswordFieldRepetirContrasena;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNombreApellidos;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
