/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.com.tic.exec.Administrador;

import src.com.tic.exec.Tecnico.*;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import javax.swing.table.DefaultTableModel;
import src.com.tic.dao.TecnicoDAOimpl;
import src.com.tic.dao.UsuarioDAOimpl;
import src.com.tic.exec.JFrameLogin;
import src.com.tic.pojo.Incidencia;

/**
 *
 * @author alumno
 */
public class VistaTecnicoAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaTecnicoAdmin.class.getName());

    private UsuarioDAOimpl usuarioDAO = new UsuarioDAOimpl();
    
    private ArrayList<String> al;
    
    int idTecnico;
    
    TecnicoDAOimpl tecnicoDAO = new TecnicoDAOimpl();

    /**
     * Creates new form VistaTecnico
     */
    public VistaTecnicoAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jLabel3.setText("Otro día más en el curro");
        try {
            al = usuarioDAO.getTiposIncidencias();
        } catch (Exception ex) {
            System.out.println("Error de búsqueda: " + ex.getMessage());
        }
        refrescarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTecnico = new javax.swing.JTable();
        jButtonCerrarIndicencia = new javax.swing.JButton();
        jButtonVerIndicenciasTiempoConcreto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerDias = new javax.swing.JSpinner();
        jButtonListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Otro dia mas en el curro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(277, 277, 277))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableTecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Incidencia", "estado", "result_cierre", "f_cierre", "f_entrada", "tipo_incidencia", "ID_Usuario", "ID_Tecnico", "descripcion", "Solucion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTecnicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTecnico);

        jButtonCerrarIndicencia.setText("Cerrar Incidencia");
        jButtonCerrarIndicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarIndicenciaActionPerformed(evt);
            }
        });

        jButtonVerIndicenciasTiempoConcreto.setText("Listar incidencia cerradas en un tiempo");
        jButtonVerIndicenciasTiempoConcreto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerIndicenciasTiempoConcretoActionPerformed(evt);
            }
        });

        jLabel2.setText("Dias");

        jButtonListar.setText("Listar Todas");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVerIndicenciasTiempoConcreto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinnerDias, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(82, 82, 82)
                        .addComponent(jButtonListar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCerrarIndicencia)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCerrarIndicencia)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonVerIndicenciasTiempoConcreto)
                        .addComponent(jSpinnerDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jButtonListar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarIndicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarIndicenciaActionPerformed
        jDialogCerrarIncidencia dCerrarIncidencia = new jDialogCerrarIncidencia(this, false);
        dCerrarIncidencia.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarIndicenciaActionPerformed

    private void jTableTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTecnicoMouseClicked

    }//GEN-LAST:event_jTableTecnicoMouseClicked

    private void jButtonVerIndicenciasTiempoConcretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerIndicenciasTiempoConcretoActionPerformed
        try {
            ArrayList<Incidencia> al = tecnicoDAO.getIncidenciasBetweenFechas((int)(this.jSpinnerDias.getValue()));
            refrescarTablaBeetwen(al);
        } catch (Exception ex) {
            System.out.println("Error al hacer consulta de fechas: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonVerIndicenciasTiempoConcretoActionPerformed

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        refrescarTabla();
    }//GEN-LAST:event_jButtonListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }
    
    public void refrescarTablaBeetwen(ArrayList<Incidencia> ai) {
        DefaultTableModel m = (DefaultTableModel) this.jTableTecnico.getModel();
        m.setNumRows(0);
        
        try {
            Incidencia i;
            for (int j = 0; j < ai.size(); j++) {
                i = ai.get(j);
                Object[] o = {
                    i.getIdIncidencia(),
                    i.getEstado(),
                    i.getResultado_cierre(),
                    i.getFechaCierre(),
                    i.getFechaEntrada(),
                    i.getTipoIncidencia(),
                    i.getIdUsuario(),
                    i.getIdTecnico(),
                    i.getDescripcionIncidencia(),
                    i.getDescripcionSolucion()
                };
                m.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar tabla incidencia");
        }
    }
    
    public void refrescarTablaPorTipo(String tipo) {
        DefaultTableModel m = (DefaultTableModel) this.jTableTecnico.getModel();
        m.setNumRows(0);
        
        Incidencia i = null;
        try {
            ArrayList<Incidencia> ai = (ArrayList<Incidencia>) tecnicoDAO.getIncidenciasByTipo(tipo);
            for (int j = 0; j < ai.size(); j++) {
                i = ai.get(j);
                Object[] o = {
                    i.getIdIncidencia(),
                    i.getEstado(),
                    i.getResultado_cierre(),
                    i.getFechaCierre(),
                    i.getFechaEntrada(),
                    i.getTipoIncidencia(),
                    i.getIdUsuario(),
                    i.getIdTecnico(),
                    i.getDescripcionIncidencia(),
                    i.getDescripcionSolucion()
                };
                m.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar tabla incidencia");
        }
    }
     
    public void refrescarTabla() {
        DefaultTableModel m = (DefaultTableModel) this.jTableTecnico.getModel();
        m.setNumRows(0);
        
        Incidencia i = null;
        try {
            ArrayList<Incidencia> ai = (ArrayList<Incidencia>) tecnicoDAO.getIncidencias();
            for (int j = 0; j < ai.size(); j++) {
                i = ai.get(j);
                Object[] o = {
                    i.getIdIncidencia(),
                    i.getEstado(),
                    i.getResultado_cierre(),
                    i.getFechaCierre(),
                    i.getFechaEntrada(),
                    i.getTipoIncidencia(),
                    i.getIdUsuario(),
                    i.getIdTecnico(),
                    i.getDescripcionIncidencia(),
                    i.getDescripcionSolucion()
                };
                m.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar tabla incidencia");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarIndicencia;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonVerIndicenciasTiempoConcreto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerDias;
    private javax.swing.JTable jTableTecnico;
    // End of variables declaration//GEN-END:variables
}
