package src.com.tic.exec.Administrador;

import javax.swing.ImageIcon;
import src.com.tic.exec.gestor.VistaGestor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tarde
 */
public class VistaAdministrador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaAdministrador.class.getName());
    private int idUsuario;
    /**
     * Creates new form NewJFrame
     */
    public VistaAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.idUsuario = idUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonGestionarDispositivos = new javax.swing.JButton();
        jButtonFuncGestor = new javax.swing.JButton();
        jButtonUsu = new javax.swing.JButton();
        jButtonGestEsp = new javax.swing.JButton();
        jButtonGestInc = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Administrador");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 60));

        jButtonGestionarDispositivos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonGestionarDispositivos.setText("GESTIONAR DISPOSITIVOS");
        jButtonGestionarDispositivos.addActionListener(this::jButtonGestionarDispositivosActionPerformed);
        getContentPane().add(jButtonGestionarDispositivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 270, -1));

        jButtonFuncGestor.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonFuncGestor.setText("FUNCIONAR COMO GESTOR");
        jButtonFuncGestor.setPreferredSize(new java.awt.Dimension(264, 28));
        jButtonFuncGestor.addActionListener(this::jButtonFuncGestorActionPerformed);
        getContentPane().add(jButtonFuncGestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 280, -1));

        jButtonUsu.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonUsu.setText("GESTIONAR USUARIOS");
        jButtonUsu.setPreferredSize(new java.awt.Dimension(264, 28));
        jButtonUsu.addActionListener(this::jButtonUsuActionPerformed);
        getContentPane().add(jButtonUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jButtonGestEsp.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonGestEsp.setText("GESTIONAR ESPACIO");
        jButtonGestEsp.setPreferredSize(new java.awt.Dimension(264, 28));
        jButtonGestEsp.addActionListener(this::jButtonGestEspActionPerformed);
        getContentPane().add(jButtonGestEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jButtonGestInc.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonGestInc.setText("FUNCIONAR COMO TECNICO");
        jButtonGestInc.setPreferredSize(new java.awt.Dimension(264, 28));
        jButtonGestInc.addActionListener(this::jButtonGestIncActionPerformed);
        getContentPane().add(jButtonGestInc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGestionarDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionarDispositivosActionPerformed
        JFrameGestionarDispositivo gestDispositivos = new JFrameGestionarDispositivo();
        gestDispositivos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonGestionarDispositivosActionPerformed

    private void jButtonFuncGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncGestorActionPerformed
        VistaGestor gestDisp = new VistaGestor();
        gestDisp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonFuncGestorActionPerformed

    private void jButtonUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuActionPerformed
        JFrameGestionarUsuario gestUsu = new JFrameGestionarUsuario();
        gestUsu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonUsuActionPerformed

    private void jButtonGestEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestEspActionPerformed
        JFrameGestionarEspacio gestEsp = new JFrameGestionarEspacio();
        gestEsp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonGestEspActionPerformed

    private void jButtonGestIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestIncActionPerformed
        
    }//GEN-LAST:event_jButtonGestIncActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> new VistaAdministrador().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFuncGestor;
    private javax.swing.JButton jButtonGestEsp;
    private javax.swing.JButton jButtonGestInc;
    private javax.swing.JButton jButtonGestionarDispositivos;
    private javax.swing.JButton jButtonUsu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
