/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.com.tic.exec.Administrador;

import src.com.tic.exec.Tecnico.*;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import javax.swing.table.DefaultTableModel;
import src.com.tic.dao.AdministradorDAOimpl;
import src.com.tic.dao.TecnicoDAOimpl;
import src.com.tic.dao.UsuarioDAOimpl;
import src.com.tic.exec.JFrameLogin;
import src.com.tic.pojo.Incidencia;

/**
 *
 * @author alumno
 */
public class VistaTecnicoAdmin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaTecnicoAdmin.class.getName());
    TecnicoDAOimpl tecnicoDAO = new TecnicoDAOimpl();
    AdministradorDAOimpl adminDAO = new AdministradorDAOimpl();
    String fecha_apertura;
    int idUsuario;
    int idTecnico;
    String tipo;
    
    
    /**
     * Creates new form VistaTecnico
     */
    public VistaTecnicoAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jLabel3.setText("Otro día más en el curro");
        refrescarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTecnico = new javax.swing.JTable();
        jButtonCerrarIndicencia = new javax.swing.JButton();
        jButtonVerIndicenciasTiempoConcreto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerDias = new javax.swing.JSpinner();
        jButtonListar = new javax.swing.JButton();
        jButtonListarVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldFecha = new javax.swing.JTextField();
        jSpinnerUsuario = new javax.swing.JSpinner();
        jSpinnerTecnico = new javax.swing.JSpinner();
        jTextFieldTipo = new javax.swing.JTextField();
        jButtonFiltros = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Otro dia mas en el curro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(277, 277, 277))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableTecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Incidencia", "estado", "result_cierre", "f_cierre", "f_entrada", "tipo_incidencia", "ID_Usuario", "ID_Tecnico", "descripcion", "Solucion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTecnicoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTecnico);

        jButtonCerrarIndicencia.setText("Cerrar Incidencia");
        jButtonCerrarIndicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarIndicenciaActionPerformed(evt);
            }
        });

        jButtonVerIndicenciasTiempoConcreto.setText("Listar incidencia cerradas en un tiempo");
        jButtonVerIndicenciasTiempoConcreto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerIndicenciasTiempoConcretoActionPerformed(evt);
            }
        });

        jLabel2.setText("Dias");

        jButtonListar.setText("Listar Todas");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });

        jButtonListarVolver.setText("Volver");
        jButtonListarVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarVolverActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 17)); // NOI18N
        jLabel1.setText("Consulta multifiltro:");

        jLabel4.setText("Fecha creación (yyyy-[m]m-[d]d):");

        jLabel5.setText("Usuario (ID):");

        jLabel6.setText("Técnico (ID):");

        jLabel7.setText("Tipo:");

        jButtonFiltros.setBackground(new java.awt.Color(51, 102, 0));
        jButtonFiltros.setText("Aplicar filtros");
        jButtonFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrosActionPerformed(evt);
            }
        });

        jButtonLimpiar.setBackground(new java.awt.Color(0, 204, 255));
        jButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/limpiar_micro.png"))); // NOI18N
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonFiltros)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLimpiar))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(jLabel4)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jSpinnerUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSpinnerTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addComponent(jTextFieldFecha)
                        .addComponent(jTextFieldTipo)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addComponent(jTextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFiltros)
                    .addComponent(jButtonLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCerrarIndicencia)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVerIndicenciasTiempoConcreto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpinnerDias, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonListar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonListarVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCerrarIndicencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVerIndicenciasTiempoConcreto)
                    .addComponent(jSpinnerDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonListar)
                        .addComponent(jButtonListarVolver)))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarIndicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarIndicenciaActionPerformed
        jDialogCerrarIncidenciaAdmin dCerrarIncidencia = new jDialogCerrarIncidenciaAdmin(this, false);
        dCerrarIncidencia.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarIndicenciaActionPerformed

    private void jTableTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTecnicoMouseClicked
        int fila = this.jTableTecnico.rowAtPoint(evt.getPoint());
        this.jTextFieldFecha.setText(((java.sql.Date)this.jTableTecnico.getValueAt(fila, 4)).toString());
        this.jSpinnerUsuario.setValue((int)this.jTableTecnico.getValueAt(fila, 6));
        this.jSpinnerTecnico.setValue((int)this.jTableTecnico.getValueAt(fila, 7));
        this.jTextFieldTipo.setText((String)this.jTableTecnico.getValueAt(fila, 5));
    }//GEN-LAST:event_jTableTecnicoMouseClicked

    private void jButtonVerIndicenciasTiempoConcretoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerIndicenciasTiempoConcretoActionPerformed
        try {
            ArrayList<Incidencia> al = tecnicoDAO.getIncidenciasBetweenFechas((int) (this.jSpinnerDias.getValue()));
            refrescarTablaBeetwen(al);
        } catch (Exception ex) {
            System.out.println("Error al hacer consulta de fechas: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonVerIndicenciasTiempoConcretoActionPerformed

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        refrescarTabla();
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jButtonListarVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarVolverActionPerformed
        VistaAdministrador atras = new VistaAdministrador();
        atras.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonListarVolverActionPerformed

    private void jButtonFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrosActionPerformed
        try {
            ArrayList<Incidencia> al = adminDAO.consultaCompuesta(this.jTextFieldFecha.getText(), (int) this.jSpinnerUsuario.getValue(), (int) this.jSpinnerTecnico.getValue(), this.jTextFieldTipo.getText());
            refrescarTablaBeetwen(al);
        } catch (Exception ex) {
            System.out.println("Error al hacer la consulta: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButtonFiltrosActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        this.jTextFieldFecha.setText("");
        this.jSpinnerUsuario.setValue(0);
        this.jSpinnerTecnico.setValue(0);
        this.jTextFieldTipo.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    public void refrescarTablaBeetwen(ArrayList<Incidencia> ai) {
        DefaultTableModel m = (DefaultTableModel) this.jTableTecnico.getModel();
        m.setNumRows(0);

        try {
            Incidencia i;
            for (int j = 0; j < ai.size(); j++) {
                i = ai.get(j);
                Object[] o = {
                    i.getIdIncidencia(),
                    i.getEstado(),
                    i.getResultado_cierre(),
                    i.getFechaCierre(),
                    i.getFechaEntrada(),
                    i.getTipoIncidencia(),
                    i.getIdUsuario(),
                    i.getIdTecnico(),
                    i.getDescripcionIncidencia(),
                    i.getDescripcionSolucion()
                };
                m.addRow(o);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void refrescarTabla() {
        DefaultTableModel m = (DefaultTableModel) this.jTableTecnico.getModel();
        m.setNumRows(0);

        Incidencia i = null;
        try {
            ArrayList<Incidencia> ai = (ArrayList<Incidencia>) adminDAO.getAllIncidencias();
            for (int j = 0; j < ai.size(); j++) {
                i = ai.get(j);
                Object[] o = {
                    i.getIdIncidencia(),
                    i.getEstado(),
                    i.getResultado_cierre(),
                    i.getFechaCierre(),
                    i.getFechaEntrada(),
                    i.getTipoIncidencia(),
                    i.getIdUsuario(),
                    i.getIdTecnico(),
                    i.getDescripcionIncidencia(),
                    i.getDescripcionSolucion()
                };
                m.addRow(o);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /*
    public static void main(String[] args) {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (Exception e) {
            System.out.println("Error de driver");
            System.exit(1);
        }
        Scanner sc = new Scanner(System.in);
        String matricula, marca, modelo, respuesta;
        do {
            System.out.println("Introduzca los filtros:");
            System.out.println("Matrícula: ");
            matricula = sc.nextLine();
            System.out.println("Marca: ");
            marca = sc.nextLine();
            System.out.println("Modelo: ");
            modelo = sc.nextLine();
            filtros(matricula, marca, modelo);
            System.out.println("¿Otra búsqueda? (S/N)");
            respuesta = sc.nextLine();
        } while (!respuesta.equalsIgnoreCase("S"));
    }*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarIndicencia;
    private javax.swing.JButton jButtonFiltros;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonListarVolver;
    private javax.swing.JButton jButtonVerIndicenciasTiempoConcreto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerDias;
    private javax.swing.JSpinner jSpinnerTecnico;
    private javax.swing.JSpinner jSpinnerUsuario;
    private javax.swing.JTable jTableTecnico;
    private javax.swing.JTextField jTextFieldFecha;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
