package src.com.tic.exec.Administrador;

import java.io.File;
import java.net.URL;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import src.com.tic.exec.JFrameLogin;
import src.com.tic.exec.gestor.VistaGestor;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author tarde
 */
public class VistaAdministrador extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaAdministrador.class.getName());
    private HelpBroker hb;

    private int idUsuario;

    /**
     * Creates new form NewJFrame
     */
    public VistaAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        inicializarAyuda();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButtonGestionarDispositivos = new javax.swing.JButton();
        jButtonFuncGestor = new javax.swing.JButton();
        jButtonUsu = new javax.swing.JButton();
        jButtonGestEsp = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonGestInc = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAyuda = new javax.swing.JMenuItem();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 400));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Administrador");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButtonGestionarDispositivos.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonGestionarDispositivos.setText("GESTIONAR DISPOSITIVOS");
        jButtonGestionarDispositivos.addActionListener(this::jButtonGestionarDispositivosActionPerformed);

        jButtonFuncGestor.setBackground(new java.awt.Color(0, 102, 102));
        jButtonFuncGestor.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonFuncGestor.setText("FUNCIONAR COMO GESTOR");
        jButtonFuncGestor.setPreferredSize(new java.awt.Dimension(264, 28));
        jButtonFuncGestor.addActionListener(this::jButtonFuncGestorActionPerformed);

        jButtonUsu.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonUsu.setText("GESTIONAR USUARIOS");
        jButtonUsu.setPreferredSize(new java.awt.Dimension(264, 28));
        jButtonUsu.addActionListener(this::jButtonUsuActionPerformed);

        jButtonGestEsp.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonGestEsp.setText("GESTIONAR ESPACIO");
        jButtonGestEsp.setPreferredSize(new java.awt.Dimension(264, 28));
        jButtonGestEsp.addActionListener(this::jButtonGestEspActionPerformed);

        jButtonRegistrar.setBackground(new java.awt.Color(51, 102, 0));
        jButtonRegistrar.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonRegistrar.setText("REGISTRAR USUARIO");
        jButtonRegistrar.addActionListener(this::jButtonRegistrarActionPerformed);

        jButtonGestInc.setBackground(new java.awt.Color(255, 153, 0));
        jButtonGestInc.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonGestInc.setForeground(new java.awt.Color(51, 51, 51));
        jButtonGestInc.setText("FUNCIONAR COMO TECNICO");
        jButtonGestInc.setPreferredSize(new java.awt.Dimension(264, 28));
        jButtonGestInc.addActionListener(this::jButtonGestIncActionPerformed);

        jMenu2.setForeground(new java.awt.Color(255, 102, 102));
        jMenu2.setText("<html><b>Salir</b></html>");

        jMenuItem1.setText("Cerrar sesión");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Ayuda");

        jMenuItemAyuda.setText("Abrir ayuda");
        jMenuItemAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemAyudaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItemAyudaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemAyudaMousePressed(evt);
            }
        });
        jMenuItemAyuda.addActionListener(this::jMenuItemAyudaActionPerformed);
        jMenu1.add(jMenuItemAyuda);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonGestInc, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonGestEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonGestionarDispositivos, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonFuncGestor, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonGestInc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonGestEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonGestionarDispositivos)
                .addGap(32, 32, 32)
                .addComponent(jButtonFuncGestor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButtonRegistrar)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGestionarDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionarDispositivosActionPerformed
        JFrameGestionarDispositivo gestDispositivos = new JFrameGestionarDispositivo();
        gestDispositivos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonGestionarDispositivosActionPerformed

    private void jButtonFuncGestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncGestorActionPerformed
        VistaGestor gestDisp = new VistaGestor();
        gestDisp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonFuncGestorActionPerformed

    private void jButtonUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuActionPerformed
        JFrameGestionarUsuario gestUsu = new JFrameGestionarUsuario();
        gestUsu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonUsuActionPerformed

    private void jButtonGestEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestEspActionPerformed
        JFrameGestionarEspacio gestEsp = new JFrameGestionarEspacio();
        gestEsp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonGestEspActionPerformed

    private void jButtonGestIncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestIncActionPerformed

        VistaTecnicoAdmin vistaTecnico = new VistaTecnicoAdmin();
        vistaTecnico.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonGestIncActionPerformed

    private void jMenuItemAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAyudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAyudaActionPerformed

    private void jMenuItemAyudaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAyudaMouseEntered
        ponLaAyuda();
    }//GEN-LAST:event_jMenuItemAyudaMouseEntered

    private void jMenuItemAyudaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAyudaMousePressed
        ponLaAyuda();
    }//GEN-LAST:event_jMenuItemAyudaMousePressed

    private void jMenuItemAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAyudaMouseClicked
        ponLaAyuda();    }//GEN-LAST:event_jMenuItemAyudaMouseClicked

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        JFrameRegister vistaRegistrar = new JFrameRegister();
        vistaRegistrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JFrameLogin login = new JFrameLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaAdministrador().setVisible(true));

    }

    private void ponLaAyuda() {
        hb.enableHelpOnButton(jMenuItemAyuda, "manual", null);
        hb.enableHelpKey(getRootPane(), "manual", null);
    }

    private void inicializarAyuda() {
        try {
            File fichero = new File("help" + File.separator + "helpset.hs");
            URL hsURL = fichero.toURI().toURL();

            HelpSet helpset = new HelpSet(getClass().getClassLoader(), hsURL);
            hb = helpset.createHelpBroker();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFuncGestor;
    private javax.swing.JButton jButtonGestEsp;
    private javax.swing.JButton jButtonGestInc;
    private javax.swing.JButton jButtonGestionarDispositivos;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonUsu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAyuda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
